### ISSUE TITLE
Can you please add a zenodo release?

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/SNData#72]
Would be nice to be able to point to what is being used!

**Comment by djperrefort** [comment]
@rbiswas4 I'm not sure I understand the request. 

Zenodo itself is not a data release, although it does *host* some astronomical data releases such as the PLaSTICC data. The `sndata` design is agnostic to where the data is being stored in the sense that there are no dedicated API constructs for the servers that host the data. Is there a specific data release that is hosted on zenodo you are interested in?

I have been thinking about adding some of the PLaSTICC simulations that Gautham ran. Although the file size on those is quite large, so I may add some protections / warnings to ensure the user knows what they are getting into. Still mulling it over.

**Comment by rbiswas4** [comment]
Sorry, I meant having a tagged version of SNData that has a zenodo doi. 

When you say  'some of PLaSTICC simulations': do you mean the simulations for the Plasticc Kaggle challenge or some of the simulations on mostly the same models but different survey strategies that have been run since?

**Comment by djperrefort** [comment]
I meant to refer to the survey strategy sims. 

I've set up Zenodo to trigger on each new release and added a DOI badge to the project README.
